<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="CliWrap" Version="3.10.5" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="10.0.12" />
    <PackageReference Include="SkiaSharp" Version="4.153.1" />
    <PackageReference Include="stateless" Version="5.20.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PhotoBooth.Abstraction\PhotoBooth.Abstraction.csproj" />
  </ItemGroup>

</Project>
