name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
          
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
          
    - name: Determine Version
    uses: gittools/actions/gitversion/execute@v0.9.7
    with:
      useConfigFile: true
      configFilePath: ./src/.github/Gitversion.yml
      
      
    - name: Display GitVersion outputs
    run: |
      echo "Major: ${{ steps.gitversion.outputs.major }}"
      echo "Minor: ${{ steps.gitversion.outputs.minor }}"
      echo "Patch: ${{ steps.gitversion.outputs.patch }}"
      echo "AssemblySemVer: ${{ steps.gitversion.outputs.assemblySemVer }}"
      echo "AssemblySemFileVer: ${{ steps.gitversion.outputs.assemblySemFileVer }}"
      
    - name: Restore dependencies
      run: dotnet restore ./src/PhotoBooth.sln
    - name: Build
      run: dotnet build -c Debug --no-restore ./src/PhotoBooth.sln
    - name: Test
      run: dotnet test -c Debug --no-build --verbosity normal ./src/PhotoBooth.sln
