name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:  
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
        
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
        
    - name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v0.9.7
      with:
        versionSpec: '5.x'
          
    - name: Determine Version
      uses: gittools/actions/gitversion/execute@v0.9.7
      with:
        useConfigFile: true
        configFilePath: ./.github/Gitversion.yml
      
    - name: Display GitVersion outputs
      run: |
        echo "Major: ${{ env.GitVersion_SemVer }}"
        echo "Major: ${{ env.GitVersion_Major }}"
        echo "Minor: ${{ env.GitVersion_Minor }}"
        echo "Patch: ${{ env.GitVersion_Patch }}"
        echo "AssemblySemVer: ${{ env.GitVersion_AssemblySemVer }}"
        echo "AssemblySemFileVer: ${{ env.GitVersion_AssemblySemFileVer }}"
      
    - name: Restore dependencies
      run: dotnet restore ./src/PhotoBooth.sln
      
    - name: Build
      run: dotnet build -c Debug -p:Version=${{ env.GitVersion_AssemblySemVer }} --no-restore ./src/PhotoBooth.sln
      
    - name: Test
      run: dotnet test -c Debug --no-build --verbosity normal ./src/PhotoBooth.sln
      
    - name: Publish application
      run: dotnet publish ./src/PhotoBooth.Server/PhotoBooth.Server.csproj -p:Version=${{ env.GitVersion_AssemblySemVer }} -r linux-arm -c Release -o publish
      
    - name: Upload artefact
      uses: actions/upload-artifact@v2
      with:
       name: "PhotoBooth.Net_${{ env.GitVersion_AssemblySemVer }}"
       path: publish
       if-no-files-found: error
